export const CITIZEN_TOKEN_KEY = "CITIZEN_TOKEN_KEY";
export const CITIZEN_FCM_TOKEN_KEY = "CITIZEN_FCM_TOKEN_KEY";
export const CITIZEN_IP = "CITIZEN_IP";
export const CITIZEN_USER_INFO = "CITIZEN_USER_INFO";
export const CITIZEN_DEFAULT_CONTENT_TYPE = 'application/json';